apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-web
spec:
  selector:
    matchLabels:
      app: app-web
  template:
    metadata:
      labels:
        app: app-web
    spec:
      containers:
      - name: app-web
        image: jmarcelotse/primeira-pipeline
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app-web
spec:
  selector:
    app: app-web
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
