name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v4

    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build da Imagem Docker
      uses: docker/build-push-action@v5
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          jmarcelotse/primeira-pipeline:v${{ github.run_number }}
          jmarcelotse/primeira-pipeline:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Adicionando a chave GPG do Google Cloud
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates gnupg
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /usr/share/keyrings/cloud.google.gpg
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -


    - name: Instalando o Plugin GKE Auth
      run: sudo apt-get update && sudo apt-get install -y google-cloud-cli-gke-gcloud-auth-plugin && sudo apt-get install -ygoogle-cloud-sdk

    - name: Obtendo o código
      uses: actions/checkout@v4

    - name: Configuração de contexto do Kubernetes
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.K8S_CONFIG_GCP }}

    - name: Execução do Manifesto
      uses: Azure/k8s-deploy@v5
      with:
        manifests: |
          ./k8s/deployment.yaml
        images: |
          jmarcelotse/primeira-pipeline:v${{ github.run_number }}
