name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v4
    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build da Imagem Docker
      uses: docker/build-push-action@v5
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          jmarcelotse/primeira-pipeline:v${{ github.run_number }}
          jmarcelotse/primeira-pipeline:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v4
    - name: Configuração de contexto do Kubernetes
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.K8S_CONFIG_GCP }}
    - name: Execução do Manifesto
      uses: Azure/k8s-deploy@v5
      with:
        manifests: |
          ./k8s/deployment.yaml
        images: |
          jmarcelotse/primeira-pipeline:v${{ github.run_number }}
