name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-lates
    steps:
    - name: Obtendo o código
    uses: actions/checkout@v4.1.5
    - name: Autenticação no Docker Hub
    uses: docker/login-action@v3.2.0
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}    
    
